### PR TITLE
Make searchbox UI more intuitive

### PR DESCRIPTION
**Pull request by karenl1**
- make typing cursor appear (blinking) when search box is selected
- get rid of weird search prompt row ("Type to search") that appeared when search box was selected and no results found

### CODE REVIEW

**Review by jerrylinew — CHANGES_REQUESTED** [review]
Let's fade the placeholder text a bit so it seems more like a placeholder text, and have it disappear right when the cursor appears, instead of when a user types (it looks strange with the cursor in the middle of the placeholder text)

**Comment by karenl1** [comment]
I made the suggested fixes, lemme know if it looks good! @jerrylinew

**Review by jerrylinew — APPROVED** [review]

**Comment by jerrylinew** [comment]
tested, looks great!

**Comment by jerrylinew** [comment]
@codeKaren changes deployed

**Pull request merged**
